### PR TITLE
Converted FT to apexcode in line with nvim-treesitter lspconfig and updated apex highlights queries

### PR DESCRIPTION
**Pull request by ethan-sargent**
Filetype changes are linked to #5. 
apexcode is the filetype used by nvim-treesitter, and so should make adoption of this tree-sitter grammar more popular.

Apex highlights.csm was updated to _include_ the SOQL highlights - I tried adding injections.scm with (soql_query) @soql and (soql_query_body) @soql to use the SOQL parser, but found poor/invalid highlighting results with bind variables (ones containing AS among others).

### CODE REVIEW

**Comment by ethan-sargent** [comment]
Closed temporarily - automated test scripts are still broken.

**Comment by aheber** [comment]
@ethan-sargent thank you for taking interest and putting forth effort.

I will not be changing all the file type definitions at this time. I would like this to work for NVIM TreeSitter but that will not be the only target so I won't be explicitly conforming.

I'm happy to entertain discussions and reasoning why the name used in this code matters. My current understanding is I should be able to keep this librarie's name and references but in the NVIM TreeSitter package we'll be able to use whatever file type references we would like as part of the config in that tool, separate from what names I use here.

`apexcode` is not a universal name for the Salesforce Apex language and as far as I can tell it is isolated to NVIM (just based on the few inputs I've received).

I also understand that the queries needed for NVIM are different than what is generally expected for TreeSitter. It seems like I need to implement a different set of queries for NVIM outside of what I implement for the base TreeSitter implementation. Looking around makes it seem like those queries are often stored in the NVIM TreeSitter library's code rather than in the syntax package.

I don't know NVIM or it's practices well, happy to help make something that fits but I'd like to make sure we keep concerns separated to their domains.

Thanks!

**Comment by ethan-sargent** [comment]
Sorry @aheber forgot to reply to your feedback.

You're right - I've done some digging and found that it shouldn't be an issue to leave as-is. I'm glad it wasn't too much effort to make the changes :) 

The queries for SOQL/SOSL are OK - I've made some changes to the semantics for operators vs keywords in SOQL in my own Neovim configuration to improve highlighting behaviour.
I think AND/OR/IN etc being keywords instead of operators is somewhat of an ambiguous change, but makes sense to some degree versus !=, = etc.

I think the SOQL and SOSL highlights don't load in Neovim because there is no language injection query, and the languages are loaded as sublanguages instead? 
Not 100% certain, will explore it at some point in the future though.

I'll probably work on some indentation queries soon though.

**Comment by aheber** [comment]
@ethan-sargent, yes I totally agree the `AND` etc being Operators. I think I threw them into Keywords because they were text, just not thinking them through.

I'm not sure on the highlights stuff, I know it is weird to have sub-languages and I've tried to configure it so they are both sub-languages and self-contained, depending on which `package.json` you look at. (some of the testing tools are weird)

The one thing that is definitely a problem that I haven't dealt with is that I don't store the compiled artifacts in the repo, mostly out of preference. if you depend on nvim to compile them for you then it doesn't seem to compile the nested languages well. It seems to really only support top-level syntaxes. I have intended to go into the the chat for that project and try and get some feedback but haven't spent the time yet. If you have any awareness or connections to figure that out that would be one of the key requirements to getting this registered as a proper option for that project.

I think the highlight files that NVIM-Treesitter needs are expected to be stored in their project, rather than being added in this one. I would expect that queries and highlights will be directly compatible with tree-sitter proper and not tuned to nvim's implementation as they do have different expectations.

I think it would make perfect sense to have another folder/sub-folder for the nvim specific queries and then to duplicate those out to the nvim-treesitter project for updates. We can figure that process cycle out later though.

Cheers!

**Pull request closed without merging**
